load(
      "@rules_cc//cc:defs.bzl"
   ,  "cc_library"
)

cc_library(
      name       = "aapFunctionalCluster_CommunicationManagement"
   ,  srcs       = ["aapFunctionalCluster_CommunicationManagement.cpp"]
#  ,  deps       = ["//repo_projects/pProjectFull/main_LATEST/source/SwcServiceEcuM:SwcServiceEcuM"]
   ,  hdrs       = [
            "interface_CommunicationManagement_VerificationStatusConfigurationByDataId.hpp"
         ,  "interface_CommunicationManagement_VerificationStatusConfigurationByFreshnessId.hpp"
         ,  "interface_CommunicationManagement_VerificationStatus.hpp"
      ]
   ,  includes   = ["."]
   ,  visibility = ["//visibility:public"]
)

